<a href="https://colab.research.google.com/github/Joeaviator/Statistics1-HW/blob/main/Statistics1_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
from google.colab import files
file = files.upload()

Saving Bestsellers with categories.csv to Bestsellers with categories.csv

In [3]:
df = pd.read_csv('Bestsellers with categories.csv')
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [4]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [6]:
Mean_User_Rating = np.mean(df['User Rating'])
print(f"Mean User rating is: {Mean_User_Rating:.1f}" )

Mean User rating is: 4.6

In [7]:
Mean_Price= np.mean(df['Price'])
print(f"Mean Price is: {Mean_Price:.1f}" )

Mean Price is: 13.1

In [8]:
Mean_R= np.mean(df['Reviews'])
print(f"Mean review is: {Mean_R:.1f}" )

Mean review is: 11953.3

In [9]:
Median_User_Rating = np.median(df['User Rating'])
print(f"Median User rating is: {Median_User_Rating:.1f}" )

Median User rating is: 4.7

In [10]:
Median_Price= np.median(df['Price'])
print(f"Median Price is: {Median_Price:.1f}" )

Median Price is: 11.0

In [11]:
Median_R= np.median(df['Reviews'])
print(f"Median review is: {Median_R:.1f}" )

Median review is: 8580.0

In [12]:
mode_User_R=df['User Rating'].mode()
print(f"Mode User rating is: {mode_User_R}" )

Mode User rating is: 0    4.8
Name: User Rating, dtype: float64

In [13]:
mode_Price=df['Price'].mode()
print(f"Mode Price is: {mode_Price}" )

Mode Price is: 0    8
Name: Price, dtype: int64

In [14]:
mode_Review=df['Reviews'].mode()
print(f"Mode Review is: {mode_Review}" )

Mode Review is: 0    8580
Name: Reviews, dtype: int64